### ISSUE TITLE
Game not opening after a computer crash/unexpected shutdown.

### ISSUE THREAD

**Issue by Dgpro5** [ismail0234/Subnautica-Below-Zero-Multiplayer#222] opened 2024-01-12 15:44 UTC
**Which version of the launcher are you using?**
-  (v6.6.6 etc.)
v.0.8.4

**Which platform are you playing the game on?**
- (Steam/Epic Games/Xbox Game Pass)
Steam

**Explain your problem**
- (Explain in as much detail as possible.)

I started playing subnautica below zero on 7 December. Today, when I started playing in multiplayer with my friend, my monitor became all black and my pc shutdown. After 5 minutes of turning on, looking at the screen (it was black) and shutdown and restarting another time, it got on. When I opened back subnautica multiplayer and tried to start my game it gives me an error: "Connection to server Failed". Looking in my games logs, I got these error. Some errors are the same cuz I tried more times. (attached)

**How can we reproduce this Bug?**
- (Describe the steps required to generate the bug.)
When playing, shutdown your PC.

**Log Files**
- (Attach the log files here.)

[2024-01-12.log](https://github.com/ismail0234/Subnautica-Below-Zero-Multiplayer/files/13920933/2024-01-12.log)

**Screenshots**
- (Fill in if available.)

**Video Records**
- (Fill in if available.)

**Comment by ismail0234** [comment] 2024-01-12 16:18
This problem is caused by the operating system. Also, I have already made a fix for this, but no new version has been released yet.

**Closed by ismail0234** 2024-01-12 16:18 UTC
Labels: Bug
